In [12]:
import csv
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt 
import matplotlib.font_manager
from sklearn import svm
from sklearn.covariance import EllipticEnvelope 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import LocalOutlierFactor
from sklearn import linear_model as lm

In [2]:
from sklearn.datasets import load_diabetes

Import danych.

In [4]:
data = load_diabetes()

In [5]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [6]:
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


Model lasso

In [ ]:
model_lasso = lm.Lasso() #(nu = 0.5,kernel="rbf", gamma=0.8)

In [17]:
model_lasso.fit(X,y)
#scores_lasso_pred = model_lasso.decision_function(X) 
y_lasso_pred = model_lasso.predict(X)

In [19]:
y_lasso_pred

array([181.08107479, 112.0218424 , 169.32345412, 154.61916593,
       129.05185212, 124.37966805, 115.33842293, 140.83926142,
       169.96589454, 187.12348139, 102.01564056, 128.69772243,
       132.0122802 , 163.29783023, 132.79802067, 157.08974182,
       184.07868719, 165.3621395 , 142.46200164, 142.48816161,
       127.28969186, 121.72737477, 131.76846868, 215.71448303,
       157.18043713, 153.12669231, 110.43351499, 168.85280616,
       143.64607586, 168.52884025, 160.01082942, 116.12034845,
       198.46653114, 128.01536871, 110.19160208, 146.98111104,
       177.71853033, 161.07209304, 200.97171822, 162.81756329,
       153.05817519, 111.23521427, 145.12156817, 129.96713344,
       187.22487058, 134.75330939, 145.20615891, 119.34563904,
       118.55180482, 168.25405857, 142.96885584, 157.61812462,
       143.0535849 , 136.49879586, 148.72836442, 113.31586471,
       177.47644915, 111.2547465 , 128.48782855, 154.60062996,
       134.58037064, 164.74764595, 123.86151396, 128.51

In [20]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

Wektor błędów

In [27]:
e=abs(y-y_lasso_pred)
e

array([3.00810748e+01, 3.70218424e+01, 2.83234541e+01, 5.13808341e+01,
       5.94814788e+00, 2.73796680e+01, 2.26615771e+01, 7.78392614e+01,
       5.99658945e+01, 1.22876519e+02, 1.01564056e+00, 5.96977224e+01,
       4.69877198e+01, 2.17021698e+01, 1.47980207e+01, 1.39102582e+01,
       1.80786872e+01, 2.13621395e+01, 4.54620016e+01, 2.55118384e+01,
       5.92896919e+01, 7.27273748e+01, 6.37684687e+01, 2.92855170e+01,
       2.68195629e+01, 4.88733077e+01, 2.65664850e+01, 8.38528062e+01,
       1.26460759e+01, 1.14471160e+02, 3.10108294e+01, 5.71203485e+01,
       1.42533469e+02, 4.10153687e+01, 4.51916021e+01, 4.49811110e+01,
       8.72814697e+01, 1.14927907e+02, 5.10282818e+01, 7.28175633e+01,
       5.30581752e+01, 5.62352143e+01, 8.41215682e+01, 3.79671334e+01,
       7.17751294e+01, 8.17533094e+01, 4.47938411e+01, 2.26543610e+01,
       4.35518048e+01, 2.62540586e+01, 1.20311442e+01, 6.73818754e+01,
       8.40535849e+01, 3.24987959e+01, 3.32716356e+01, 1.46841353e+01,
      

10% outlierów - największe wartości z wektora błędów

In [32]:
e2=e.argsort()[-44:][::-1]

In [33]:
e2

array([359,  32, 290, 102, 190, 138, 141, 152, 404, 362, 256,  56, 113,
       289,   9, 304, 204, 217, 360, 156, 150,  37,  29, 117,  92, 222,
       417,  78, 364, 250, 238, 428, 137, 276, 280,  75, 236, 254, 232,
       328, 129, 336, 297, 262], dtype=int64)

In [71]:
e[262]

97.6659950786489

In [72]:
ground_truth = np.digitize(e,bins=[0,e[262]])

In [79]:
ground_truth[ground_truth==2]=-1

In [92]:
ground_truth

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1, -1,  1,  1,  1

Modele SVM i CLF

In [82]:
model_svm = svm.OneClassSVM(nu = 0.5,kernel="rbf", gamma=0.8)

In [83]:
model_svm.fit(X)
scores_svn_pred = model_svm.decision_function(X) 
y_svm_pred = model_svm.predict(X)

In [84]:
clf = LocalOutlierFactor(n_neighbors=30)
y_clf_pred = clf.fit_predict(X)
scores_clf_pred = clf.negative_outlier_factor_

In [85]:
y_svm_pred

array([ 1, -1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1,
        1,  1,  1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1, -1, -1,
       -1, -1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1,
        1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1,  1,  1,
        1, -1,  1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1,
        1, -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1,  1,
        1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1,
       -1,  1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1, -1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1, -1,
        1,  1, -1, -1, -1

In [86]:
y_clf_pred

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

Sprawdzenie pod kątem zbieżności wyników

In [87]:
n_svm_errors = (y_svm_pred != ground_truth).sum()

In [88]:
n_clf_errors = (y_clf_pred != ground_truth).sum()

In [90]:
n_svm_errors

219

In [91]:
n_clf_errors

45

Bardziej zgodny z modelem lasso jest n_clf_errors.